name: Deploy Page to Production

on:
  push:
    branches: 
      - develop
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy page
        uses: JamesIves/github-pages-deploy-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: build
          CLEAN: true
          SINGLE_COMMIT: true
